### ISSUE TITLE
About USB camera

### ISSUE THREAD

**Issue by Kingkunkkk** [Credntia/CVScanner#12]
I tried to insert a USB camera  on the industrial control panel,but I cannot capture the picture what I want. What's the reason?

**Comment by iamMehedi** [comment]
This library is for Android phones/tablets. And if the device you are trying on is running on android and this library can't find/operate the camera that might be a platform/device driver/api issue rather than a issue with this library. If you can provide the device & OS details and list the stuff that you've tried I can take a look and share my insights.
